name: flutter_app_publisher
description: Flutter app publisher
version: 0.4.2
homepage: https://distributor.leanflutter.dev
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/flutter_app_publisher

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  dio: ^5.3.4
  dio_cookie_manager: 3.1.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  parse_app_package: ^0.4.0
  pubspec_parse: ^1.1.0
  qiniu_sdk_base: ^0.5.0
  shell_executor: ^0.1.5
  encrypt: ^5.0.3
  crypto: ^3.0.3
  pretty_dio_logger: 1.3.1
  flutter_oss_aliyun: 6.4.2
  dart_jsonwebtoken: ^2.14.1
  jose: ^0.3.4

dev_dependencies:
  dependency_validator: ^3.0.0
